// Generated by scripts/tracker/generate-tracker-v2.py. Do not edit.
// Chunks must be fetched in order; accounts are pre-sorted across files.
// Empty unless generated with --emit-public-chunks: the tracker reads
// the query function instead, and the dataset is not published.
export const TRACKER_V2_ACCOUNT_CHUNKS = [] as const;
