// Generated by scripts/tracker/generate-static-accounts.py. Do not edit.
// Chunks must be fetched in order; accounts are pre-sorted across files.
export const TRACKER_ACCOUNT_CHUNKS = [
  "/data/t/1a4455f479a057d6.json",
  "/data/t/92650c6a79a3a4fb.json",
  "/data/t/f1948d16e51aad1a.json",
  "/data/t/e5b41b4e0f3a2c2d.json",
  "/data/t/2b046dabb6efc89e.json",
  "/data/t/23362be0f4948041.json",
  "/data/t/95fb69194dfafbc9.json",
  "/data/t/6fc3dc9b8608ab98.json",
] as const;
