// Generated by scripts/tracker/generate-static-accounts.py. Do not edit.
// Chunks must be fetched in order; accounts are pre-sorted across files.
export const TRACKER_ACCOUNT_CHUNKS = [
  "/data/t/59dcf16ac3394b00.json",
  "/data/t/602829b479b670be.json",
  "/data/t/7d14688a013ff883.json",
  "/data/t/e3008c92dc442a24.json",
  "/data/t/93c4e7843d1cfd5f.json",
  "/data/t/b700b5968d40347c.json",
  "/data/t/db9a292e0dec9e50.json",
  "/data/t/53e0609affac714b.json",
] as const;
