// Generated by scripts/tracker/generate-tracker-v2.py. Do not edit.
// Chunks must be fetched in order; accounts are pre-sorted across files.
export const TRACKER_V2_ACCOUNT_CHUNKS = [
  "/data/t2/d5a4607bc6d072bf.json",
  "/data/t2/78687ce04bbd034f.json",
  "/data/t2/f99fb0856d230841.json",
  "/data/t2/facde4c4ad4e05d8.json",
  "/data/t2/607e9f9719dfbee0.json",
  "/data/t2/faff5ef8e5b6242c.json",
  "/data/t2/f4cda85d642bb8c2.json",
  "/data/t2/b666e53975d881ad.json",
] as const;
