// Generated by scripts/tracker/generate-static-accounts.py. Do not edit.
// Chunks must be fetched in order; accounts are pre-sorted across files.
export const TRACKER_ACCOUNT_CHUNKS = [
  "/data/t/1997cc8e5243df32.json",
  "/data/t/f90080f3bd4e2058.json",
  "/data/t/bf6a3069bdd04420.json",
  "/data/t/68c1170e6d9ef2e1.json",
  "/data/t/4e56db89b79c1a2a.json",
  "/data/t/3e0095851f1ead50.json",
  "/data/t/0883faf401866790.json",
  "/data/t/55ae3edcc29c4537.json",
] as const;
