#!/usr/bin/env node
// Post-build step: rewrite the GCC block of the sitemap with every generated
// GCC URL (the /gcc directory, its paginated pages, the industry/city landing
// pages and the published company pages), then write dist/sitemap.xml.
//
// public/sitemap.xml stays the hand-maintained base; everything between the
// <!-- gcc:start --> / <!-- gcc:end --> markers is generated here.
//
// Runs after generate-landing-pages.mjs (see package.json build script).

import { readFile, writeFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import {
  DIRECTORY_PAGE_SIZE,
  DIST,
  ROOT,
  SITE,
  landingSets,
  loadAccounts,
  publicAccounts,
} from "./prerender-lib.mjs";

const BASE = join(ROOT, "public", "sitemap.xml");
const OUT = join(DIST, "sitemap.xml");

const url = (loc, changefreq, priority) =>
  `  <url>\n    <loc>${loc}</loc>\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`;

const accounts = await loadAccounts();
const pub = publicAccounts(accounts);
const sets = landingSets(accounts);

const entries = [url(`${SITE}/gcc`, "weekly", "0.9")];

const pageCount = Math.ceil(pub.length / DIRECTORY_PAGE_SIZE);
for (let n = 1; n <= pageCount; n++) {
  entries.push(url(`${SITE}/gcc/directory/${n}`, "weekly", "0.6"));
}
for (const set of [...sets.industries, ...sets.cities]) {
  entries.push(url(`${SITE}${set.path.replace(/\/$/, "")}`, "weekly", "0.7"));
}

// Published company pages only (public/gcc/companies/<slug>/index.html).
const companiesDir = join(ROOT, "public", "gcc", "companies");
if (existsSync(companiesDir)) {
  for (const slug of (await readdir(companiesDir)).sort()) {
    if (existsSync(join(companiesDir, slug, "index.html"))) {
      entries.push(url(`${SITE}/gcc/companies/${slug}`, "monthly", "0.7"));
    }
  }
}

const base = await readFile(BASE, "utf8");
const block = `<!-- gcc:start (generated by scripts/gcc/generate-sitemap.mjs) -->\n${entries.join("\n")}\n  <!-- gcc:end -->`;
if (!/<!-- gcc:start[\s\S]*?gcc:end -->/.test(base)) {
  console.error("public/sitemap.xml is missing the <!-- gcc:start --> / <!-- gcc:end --> markers.");
  process.exit(1);
}
const out = base.replace(/<!-- gcc:start[\s\S]*?gcc:end -->/, block);
await writeFile(OUT, out);
console.log(`Wrote ${OUT} with ${entries.length} GCC URLs`);
